2020-06-18 14:48:58,567 ERROR: Exception on / [GET] [in C:\Python34\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python34\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\main\routes.py", line 53, in index_9
    return render_template('index_9.html', title='Home')
  File "C:\Python34\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Python34\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Python34\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\base.html", line 100, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 11, in block "content"
    <a href="{{ url_for('visitor_home') }}" class="button2">Visitor</a>
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Python34\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Python34\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'visitor_home'. Did you mean 'main.visitor_home' instead?
2020-06-18 14:49:07,789 ERROR: Exception on /index_9 [GET] [in C:\Python34\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python34\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\main\routes.py", line 53, in index_9
    return render_template('index_9.html', title='Home')
  File "C:\Python34\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Python34\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Python34\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\base.html", line 100, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 11, in block "content"
    <a href="{{ url_for('visitor_home') }}" class="button2">Visitor</a>
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Python34\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Python34\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'visitor_home'. Did you mean 'main.visitor_home' instead?
2020-06-18 14:49:10,042 ERROR: Exception on /index_9 [GET] [in C:\Python34\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python34\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\main\routes.py", line 53, in index_9
    return render_template('index_9.html', title='Home')
  File "C:\Python34\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Python34\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Python34\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Python34\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\base.html", line 100, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Downloads\microblog-0.18\microblog-0.18\app\templates\index_9.html", line 11, in block "content"
    <a href="{{ url_for('visitor_home') }}" class="button2">Visitor</a>
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Python34\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Python34\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'visitor_home'. Did you mean 'main.visitor_home' instead?
2020-06-18 14:49:58,752 INFO: Microblog startup [in E:\Downloads\microblog-0.18\microblog-0.18\app\__init__.py:82]
